paths:
  /api/v1/workspaces:
    get:
      tags:
        - Workspaces
      summary: List user's workspaces
      description: Get all workspaces for the authenticated user
      security:
        - cookieAuth: []
      responses:
        200:
          description: List of workspaces
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Workspace"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - Workspaces
      summary: Create workspace
      description: Create a new workspace for the authenticated user
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - template
                - language
                - libraries
              properties:
                name:
                  type: string
                  description: Workspace name
                template:
                  type: string
                  description: Template type (e.g., react, node)
                language:
                  type: string
                  description: Programming language
                libraries:
                  type: array
                  items:
                    type: string
                  description: List of libraries to include
                description:
                  type: string
                  description: Workspace description
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                      description: CPU allocation (e.g., "500m")
                    memory:
                      type: string
                      description: Memory allocation (e.g., "1Gi")
      responses:
        201:
          description: Workspace created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workspace"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/workspaces/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Workspaces
      summary: Get workspace
      description: Get details of a specific workspace
      security:
        - cookieAuth: []
      responses:
        200:
          description: Workspace details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workspace"
        401:
          description: Unauthorized
        404:
          description: Workspace not found

    put:
      tags:
        - Workspaces
      summary: Update workspace
      description: Update workspace details
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
      responses:
        200:
          description: Workspace updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workspace"
        401:
          description: Unauthorized
        404:
          description: Workspace not found

    delete:
      tags:
        - Workspaces
      summary: Delete workspace
      description: Delete a specific workspace
      security:
        - cookieAuth: []
      responses:
        200:
          description: Workspace deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        401:
          description: Unauthorized
        404:
          description: Workspace not found

components:
  schemas:
    Workspace:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        userId:
          type: string
          format: uuid
        template:
          type: string
        language:
          type: string
        libraries:
          type: array
          items:
            type: string
        description:
          type: string
        resources:
          type: object
          properties:
            cpu:
              type: string
            memory:
              type: string
        status:
          type: string
          enum: [creating, running, stopped, failed]
        editorConfig:
          type: object
        editorLayout:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
