components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /workspace:
    post:
      summary: Create a new workspace
      tags: [Workspace]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workspaceId:
                  type: string
                  example: "example-id"
      responses:
        "201":
          description: Workspace created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Workspace created successfully"
                  result:
                    type: object
                    properties:
                      workspaceId:
                        type: string
                        example: "example-id"
